### ISSUE TITLE
Consider merging back into original tsyringe

### ISSUE THREAD

**Issue by Xapphire13** [skiptirengu/tsyringex#1]
I assume this forks comes from the relatively slow reviews over at https://github.com/microsoft/tsyringe. I apologize for the slow reviews (the core tsyringe team is just 2 people) and I don't want that to dissuade people from adding to it.

I have just merged in the multi-registration PR and I encourage you to keep contributing to the original =].

**Comment by sugiruu** [comment]
Thanks for reviewing the PR's!
Closing in favor of microsoft/tsyringe#61.
